import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, ReferenceLine } from 'recharts';
import { money } from '../../shared/finance';
import { Empty } from './ui';
export const chartColors=['#8172d5','#b3a5ec','#f2b880','#72b8a4','#81a9df','#d38bac'];
const tip={borderRadius:12,border:'1px solid var(--border)',background:'var(--surface)',color:'var(--text)',fontSize:12};
const axis={fontSize:11,fill:'#9694a6'};
export function FlowChart({data,height=240}:{data:Record<string,unknown>[];height?:number}){return <ResponsiveContainer width="100%" height={height}><BarChart data={data} barGap={6} margin={{top:15,right:5,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--border)"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={axis} dy={8}/><YAxis tickFormatter={v=>`${v/1000}k`} axisLine={false} tickLine={false} tick={axis}/><Tooltip contentStyle={tip} cursor={{fill:'var(--hover)'}} formatter={v=>money(Number(v))}/><Bar isAnimationActive={false} name="Income" dataKey="income" fill="#8172d5" radius={[5,5,0,0]} maxBarSize={21}/><Bar isAnimationActive={false} name="Expenses" dataKey="expenses" fill="#d5cdf3" radius={[5,5,0,0]} maxBarSize={21}/></BarChart></ResponsiveContainer>;}
export function Donut({data,total}:{data:{name:string;value:number;color?:string}[];total:number}){if(!data.some(d=>d.value>0))return <Empty text="Your spending breakdown will appear here."/>;return <div className="donut-wrap"><div className="donut-chart"><ResponsiveContainer width="100%" height={210}><PieChart><Pie isAnimationActive={false} data={data} dataKey="value" innerRadius={68} outerRadius={88} paddingAngle={3} stroke="none">{data.map((x,i)=><Cell key={x.name} fill={x.color||chartColors[i%chartColors.length]}/>)}</Pie><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/></PieChart></ResponsiveContainer><div className="donut-center"><small>Total spent</small><strong>{money(total)}</strong></div></div><div className="donut-legend">{data.slice(0,6).map((x,i)=><div key={x.name}><span className="dot" style={{background:x.color||chartColors[i%chartColors.length]}}/><span>{x.name}</span><strong>{total?(x.value/total*100).toFixed(0):0}%</strong></div>)}</div></div>;}
export function SpendingChart({data,average}:{data:Record<string,unknown>[];average:number}){return <ResponsiveContainer width="100%" height={200}><AreaChart data={data} margin={{left:-20,right:8,top:15}}><defs><linearGradient id="spending-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8172d5" stopOpacity={0.25}/><stop offset="100%" stopColor="#8172d5" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="name" tick={axis} axisLine={false} tickLine={false} minTickGap={30}/><YAxis tick={axis} tickFormatter={v=>`${v/1000}k`} axisLine={false} tickLine={false}/><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/><ReferenceLine y={average} stroke="#c5bcdf" strokeDasharray="4 4"/><Area isAnimationActive={false} name="Spent" dataKey="amount" type="monotone" stroke="#8172d5" strokeWidth={2.5} fill="url(#spending-fill)"/></AreaChart></ResponsiveContainer>;}
export function ComparisonChart({data}:{data:Record<string,unknown>[]}){return <ResponsiveContainer width="100%" height={Math.max(220,data.length*38)}><BarChart layout="vertical" data={data} margin={{left:20,right:10}}><XAxis type="number" tick={axis} tickFormatter={v=>`${v/1000}k`} axisLine={false}/><YAxis type="category" dataKey="name" width={100} tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/><Legend/><Bar isAnimationActive={false} name="Previous" dataKey="previous" fill="#d5cdf3" radius={3}/><Bar isAnimationActive={false} name="Current" dataKey="current" fill="#8172d5" radius={3}/></BarChart></ResponsiveContainer>;}
export function TrendChart({data,keys=['savings']}:{data:Record<string,unknown>[];keys?:string[]}){return <ResponsiveContainer width="100%" height={240}><LineChart data={data} margin={{left:-10,right:15,top:10}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="name" tick={axis}/><YAxis tick={axis} tickFormatter={v=>`${v/1000}k`}/><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/><Legend/>{keys.map((k,i)=><Line isAnimationActive={false} key={k} type="monotone" name={k} dataKey={k} stroke={chartColors[i%chartColors.length]} strokeWidth={2.5} dot={false}/>)}</LineChart></ResponsiveContainer>;}

