import { useRef, useState } from 'react';
import { Camera, Download, FileText, Image as ImageIcon, Paperclip, Upload, X, ChevronLeft, ChevronRight, ZoomIn, ZoomOut } from 'lucide-react';
import { toast } from 'sonner';
import type { Attachment } from '../../shared/schema';
import { uid } from '../../shared/finance';
import { api, useStore } from '../lib';
import { Button } from './ui';
import { useConfirm } from './ConfirmProvider';

const accepted=['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf'];
const read=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});
async function prepare(file:File){if(file.size>5*1024*1024)throw new Error(`${file.name} is larger than 5 MB.`);if(!accepted.includes(file.type)&&!file.name.toLowerCase().match(/\.(jpe?g|png|webp|heic|heif|pdf)$/))throw new Error(`${file.name} is not a supported image or PDF.`);if(!['image/jpeg','image/png','image/webp'].includes(file.type))return read(file);const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=reject;el.src=url;});if(img.width<=1600)return read(file);const scale=1600/img.width,canvas=document.createElement('canvas');canvas.width=1600;canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL(file.type==='image/png'?'image/png':'image/jpeg',.82);}finally{URL.revokeObjectURL(url);}}

export function ProofBadge({count,onClick}:{count:number;onClick?:()=>void}){return count?<button type="button" className="proof-badge" onClick={onClick}><Paperclip size={12}/>{count}</button>:null;}
export function ProofGallery({files,compact=false}:{files:Attachment[];compact?:boolean}){const [index,setIndex]=useState<number|null>(null),[zoom,setZoom]=useState(1);if(!files.length)return null;const active=index===null?null:files[index];return <><div className={'proof-gallery '+(compact?'compact':'')}>{files.map((file,i)=>file.file_type==='pdf'?<a key={file.id} href={file.file_url} target="_blank" rel="noreferrer" className="proof-thumb" title={file.file_name}><FileText/><small>PDF</small></a>:<button type="button" className="proof-thumb" key={file.id} onClick={()=>{setIndex(i);setZoom(1);}}><img src={file.file_url} alt={file.file_name}/></button>)}</div>{active&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Proof viewer"><button className="lightbox-close" aria-label="Close proof viewer" onClick={()=>setIndex(null)}><X/></button><div className="lightbox-tools"><button aria-label="Zoom out" onClick={()=>setZoom(Math.max(.5,zoom-.25))}><ZoomOut/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(Math.min(3,zoom+.25))}><ZoomIn/></button><a aria-label="Download proof" href={active.file_url} download={active.file_name}><Download/></a></div>{files.length>1&&<><button className="lightbox-prev" aria-label="Previous proof" onClick={()=>{setIndex((index!-1+files.length)%files.length);setZoom(1);}}><ChevronLeft/></button><button className="lightbox-next" aria-label="Next proof" onClick={()=>{setIndex((index!+1)%files.length);setZoom(1);}}><ChevronRight/></button></>}<div className="lightbox-stage">{active.file_type==='pdf'?<iframe title={active.file_name} src={active.file_url}/>:<img src={active.file_url} alt={active.file_name} style={{transform:`scale(${zoom})`}}/>}</div><div className="lightbox-name">{active.file_name} · {index!+1} of {files.length}</div></div>}</>;
}
export function ProofUploader({files,onChange,owner}:{files:Attachment[];onChange:(files:Attachment[])=>void;owner:{ledger_entry_id:string}|{repayment_id:string}}){const {demo}=useStore(),confirm=useConfirm(),input=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),[drag,setDrag]=useState(false),[progress,setProgress]=useState('');const add=async(list:FileList|File[])=>{const incoming=Array.from(list);if(files.length+incoming.length>5){toast.error('Up to 5 proof files are allowed per record.');return;}const next=[...files];for(const file of incoming){try{setProgress(`Preparing ${file.name}…`);const data=await prepare(file);let file_url=data,id=uid();if(!demo){setProgress(`Uploading ${file.name}…`);const uploaded=await api('/proofs','POST',{data_url:data,file_name:file.name});id=uploaded.id;file_url=uploaded.file_url;}next.push({id,...owner,file_url,file_name:file.name,file_type:file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')?'pdf':'image',uploaded_at:new Date().toISOString()});onChange([...next]);}catch(e){toast.error((e as Error).message);}}setProgress('');};const remove=async(file:Attachment)=>{if(await confirm({title:'Remove proof file?',description:`${file.file_name} will be removed when you save this record.`,confirmLabel:'Remove proof',danger:true}))onChange(files.filter(f=>f.id!==file.id));};return <div className="proof-uploader"><div className={'proof-drop '+(drag?'dragging':'')} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void add(e.dataTransfer.files);}} onClick={()=>input.current?.click()} role="button" tabIndex={0} onKeyDown={e=>e.key==='Enter'&&input.current?.click()}><Upload size={22}/><b>Drop proof here or browse</b><small>JPG, PNG, WEBP, HEIC or PDF · max 5 MB · up to 5 files</small><input ref={input} hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf,.heic,.heif" onChange={e=>e.target.files&&void add(e.target.files)}/></div><Button type="button" variant="outline" className="camera-button" onClick={()=>camera.current?.click()}><Camera size={15}/>Take a photo</Button><input ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files&&void add(e.target.files)}/>{progress&&<div className="upload-progress"><span/>{progress}</div>}<div className="proof-previews">{files.map(file=><div key={file.id}>{file.file_type==='pdf'?<FileText/>:<img src={file.file_url} alt=""/>}<span title={file.file_name}>{file.file_name}</span><button type="button" aria-label={`Remove ${file.file_name}`} onClick={()=>void remove(file)}><X size={14}/></button></div>)}</div>{demo&&files.length>0&&<small className="proof-note">Demo proofs are stored as base64 data in this browser.</small>}</div>;}
