import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { format } from 'date-fns';
import { toast } from 'sonner';
import type { Transaction } from '../../shared/schema';
import { uid } from '../../shared/finance';
import { useStore } from '../lib';
import { Button, Modal } from './ui';
const formSchema=z.object({amount:z.number().positive('Enter an amount above zero').max(1e12),date:z.string().min(1,'Choose a date'),note:z.string().max(500),category_id:z.string(),source_type:z.enum(['Salary','Freelance','Business','Rental','Bonus','Interest','Gift','Other']),payment_method:z.enum(['Cash','UPI','Card','Bank Transfer']),is_recurring:z.boolean(),tags:z.string()});
type Fields=z.infer<typeof formSchema>;
export function TransactionForm({kind,entry,onClose}:{kind:'incomes'|'expenses';entry?:Transaction;onClose:()=>void}){const {state:s,save,saving}=useStore();const {register,handleSubmit,formState:{errors}}=useForm<Fields>({resolver:zodResolver(formSchema),defaultValues:{amount:entry?.amount,date:entry?.date||format(new Date(),'yyyy-MM-dd'),note:entry?.note||'',category_id:entry?.category_id||s!.categories[0]?.id||'',source_type:entry?.source_type||'Salary',payment_method:entry?.payment_method||'UPI',is_recurring:entry?.is_recurring||false,tags:entry?.tags.join(', ')||''}});
 const submit=async(v:Fields)=>{const next=structuredClone(s!);const record:Transaction={...v,id:entry?.id||uid(),tags:v.tags.split(',').map(t=>t.trim()).filter(Boolean),recurrence_id:entry?.recurrence_id};if(kind==='incomes')delete record.category_id;else delete record.source_type;if(entry)next[kind]=next[kind].map(t=>t.id===entry.id?record:t);else next[kind].push(record);if(await save(next)){toast.success(entry?'Transaction updated':'Transaction added');onClose();}};
 return <Modal open onClose={onClose} title={`${entry?'Edit':'Add'} ${kind==='incomes'?'income':'expense'}`}><form onSubmit={handleSubmit(submit)} className="form-grid"><label className="full">Amount (₹)<input autoFocus type="number" step="0.01" placeholder="0.00" {...register('amount',{valueAsNumber:true})}/>{errors.amount&&<small className="error">{errors.amount.message}</small>}</label><label>Date<input type="date" {...register('date')}/></label>{kind==='incomes'?<label>Source<select {...register('source_type')}>{['Salary','Freelance','Business','Rental','Bonus','Interest','Gift','Other'].map(x=><option key={x}>{x}</option>)}</select></label>:<label>Category<select {...register('category_id')}>{s!.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{kind==='expenses'&&<label>Payment method<select {...register('payment_method')}>{['UPI','Card','Cash','Bank Transfer'].map(x=><option key={x}>{x}</option>)}</select></label>}<label className="full">Note<input placeholder="What's this for?" {...register('note')}/></label><label className="full">Tags<input placeholder="work, travel" {...register('tags')}/></label><label className="checkbox full"><input type="checkbox" {...register('is_recurring')}/>Repeat monthly on this date</label>{Object.entries(errors).filter(([k])=>k!=='amount').map(([k,v])=><small className="error" key={k}>{v.message}</small>)}<div className="form-actions full"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={saving}>{saving?'Saving…':'Save transaction'}</Button></div></form></Modal>;
}
