import { addMonths, format, getDaysInMonth, startOfMonth, differenceInCalendarMonths } from 'date-fns';
import type { State, Transaction, Loan, LedgerEntry } from './schema';
export const uid=()=>crypto.randomUUID();
export const monthKey=(d=new Date())=>format(d,'yyyy-MM');
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export const sum=(a:{amount:number}[])=>a.reduce((s,x)=>s+x.amount,0);
export const inMonth=(a:Transaction[],month:string)=>a.filter(x=>x.date.startsWith(month));
export const change=(current:number,previous:number)=>previous===0?(current===0?0:null):(current-previous)/Math.abs(previous)*100;
export function totals(s:State,m:string){const income=sum(inMonth(s.incomes,m)),expenses=sum(inMonth(s.expenses,m));return {income,expenses,balance:income-expenses,savings:income-expenses,rate:income?(income-expenses)/income*100:0,emi:sum(s.emi_payments.filter(p=>p.month===m&&p.status==='paid'))};}
export function emiAmount(p:number,annual:number,n:number){const r=annual/1200;return r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;}
export function tenureForEmi(p:number,annual:number,emi:number){
 if(p<=0||emi<=0)return 0;
 const r=annual/1200;
 if(!r)return Math.ceil(p/emi);
 if(emi<=p*r)return Infinity;
 return Math.ceil(Math.log(emi/(emi-p*r))/Math.log(1+r));
}
export function amortization(loan:Loan){let balance=loan.principal;return Array.from({length:loan.tenure_months},(_,i)=>{const interest=balance*loan.interest_rate/1200;const principal=Math.min(balance,Math.max(0,loan.emi_amount-interest));balance=Math.max(0,balance-principal);return {month:i+1,interest,principal,balance};});}
export function elapsedDays(month:string,now=new Date()){const date=new Date(month+'-01T12:00:00');return month<monthKey(now)?getDaysInMonth(date):month>monthKey(now)?0:now.getDate();}
export function forecast(s:State,m:string,now=new Date()){const elapsed=elapsedDays(m,now); const spent=sum(inMonth(s.expenses,m).filter(e=>e.date<=format(now,'yyyy-MM-dd')));return elapsed?Math.round(spent/elapsed*getDaysInMonth(new Date(m+'-01T12:00:00'))*100)/100:0;}
export function health(s:State,m:string){const t=totals(s,m);if(!t.income)return 0;const burden=s.emis.filter(e=>e.status==='active').reduce((v,e)=>v+e.emi_amount,0)/t.income;const budgets=s.budgets.filter(b=>b.month===m);const adherence=budgets.length?budgets.filter(b=>sum(inMonth(s.expenses,m).filter(e=>e.category_id===b.category_id))<=b.limit_amount).length/budgets.length:0.5;return Math.round(Math.min(1,Math.max(0,t.rate/20))*40+Math.max(0,1-burden)*30+adherence*30);}
export function accruedInterest(entry:LedgerEntry,asOf=new Date()){if(entry.no_return_expected||!entry.interest_enabled||!entry.interest_rate)return 0;const end=Math.max(Date.parse(entry.date+'T12:00:00'),asOf.getTime());const days=Math.floor((end-Date.parse(entry.date+'T12:00:00'))/86400000);return entry.amount*entry.interest_rate*days/36500;}
export function ledgerRepaid(s:State,entryId:string){return sum(s.repayments.filter(r=>r.ledger_entry_id===entryId));}
export function ledgerPending(s:State,entry:LedgerEntry,asOf=new Date()){if(entry.no_return_expected)return 0;return Math.max(0,entry.amount+accruedInterest(entry,asOf)-ledgerRepaid(s,entry.id)-entry.written_off_amount);}
export function ledgerStatus(s:State,entry:LedgerEntry,asOf=new Date()){if(entry.no_return_expected)return 'NO_RETURN_EXPECTED';const pending=ledgerPending(s,entry,asOf),repaid=ledgerRepaid(s,entry.id);if(pending<=0.01)return entry.written_off_amount>=entry.amount?'WRITTEN_OFF':'SETTLED';if(entry.due_date&&entry.due_date<format(asOf,'yyyy-MM-dd'))return 'OVERDUE';return repaid>0||entry.written_off_amount>0?'PARTIAL':'PENDING';}
export function ledgerSummary(s:State,asOf=new Date()){let toReceive=0,toPay=0,overdue=0,overdueCount=0;for(const entry of s.ledger_entries){const pending=ledgerPending(s,entry,asOf);if(entry.direction==='GAVE')toReceive+=pending;else toPay+=pending;if(ledgerStatus(s,entry,asOf)==='OVERDUE'){overdue+=pending;overdueCount++;}}const year=String(asOf.getFullYear());const lentThisYear=sum(s.ledger_entries.filter(e=>e.direction==='GAVE'&&!e.no_return_expected&&e.date.startsWith(year)));const recovered=sum(s.repayments.filter(r=>r.date.startsWith(year)&&s.ledger_entries.some(e=>e.id===r.ledger_entry_id&&e.direction==='GAVE'&&!e.no_return_expected)));return {toReceive,toPay,net:toReceive-toPay,overdue,overdueCount,lentThisYear,recovered,recoveryRate:lentThisYear?recovered/lentThisYear*100:0};}
export function ledgerMonth(s:State,m:string){const lent=sum(s.ledger_entries.filter(e=>e.direction==='GAVE'&&e.date.startsWith(m))),borrowed=sum(s.ledger_entries.filter(e=>e.direction==='TOOK'&&e.date.startsWith(m)));let recovered=0,repaid=0;for(const r of s.repayments.filter(r=>r.date.startsWith(m))){const e=s.ledger_entries.find(e=>e.id===r.ledger_entry_id);if(e?.direction==='GAVE')recovered+=r.amount;else if(e?.direction==='TOOK')repaid+=r.amount;}return {lent,borrowed,recovered,repaid};}
export function cashBalance(s:State,m:string){const t=totals(s,m),l=ledgerMonth(s,m);return t.balance-l.lent+l.recovered+l.borrowed-l.repaid;}
export function salaryCreditDate(month:string,profile:State['profile']){const [year,oneBasedMonth]=month.split('-').map(Number),last=new Date(year,oneBasedMonth,0,12);if(profile.salary_credit_rule==='fixed'){const day=Math.min(profile.salary_credit_day,last.getDate());return `${month}-${String(day).padStart(2,'0')}`;}let date=last;while(date.getDay()===0||date.getDay()===6)date=new Date(date.getFullYear(),date.getMonth(),date.getDate()-1,12);if(profile.salary_credit_rule==='before_last_working_day'){date=new Date(date.getFullYear(),date.getMonth(),date.getDate()-1,12);while(date.getDay()===0||date.getDay()===6)date=new Date(date.getFullYear(),date.getMonth(),date.getDate()-1,12);}return format(date,'yyyy-MM-dd');}
export function materializeRecurring(s:State,now=new Date()):State {const next=structuredClone(s) as State;next.people??=[];next.ledger_entries??=[];next.repayments??=[];next.attachments??=[];next.profile.salary_credit_rule??='fixed';next.profile.monthly_salary??=0;for(const key of ['incomes','expenses'] as const){const original=next[key].filter(t=>t.is_recurring&&!t.recurrence_id&&!t.emi_id);for(const t of original){const start=new Date(t.date+'T12:00:00');const count=differenceInCalendarMonths(now,start);for(let i=1;i<=Math.min(count,1200);i++){const targetMonth=monthKey(addMonths(start,i));if(key==='incomes'&&t.salary_schedule&&next.profile.salary_credit_rule==='manual')continue;const date=key==='incomes'&&t.salary_schedule?salaryCreditDate(targetMonth,next.profile):format(addMonths(start,i),'yyyy-MM-dd');if(date>format(now,'yyyy-MM-dd'))continue;const recordId=`rec-${t.id}-${targetMonth}`;if(!next[key].some(x=>x.id===recordId))next[key].push({...t,id:recordId,date,amount:key==='incomes'&&t.salary_schedule&&next.profile.monthly_salary?next.profile.monthly_salary:t.amount,is_recurring:false,recurrence_id:t.id});}}}return next;}
export function payEmi(s:State,id:string,month:string):State{const next=structuredClone(s),loan=next.emis.find(e=>e.id===id);if(!loan||loan.status==='closed')throw new Error('This loan is closed');if(month<loan.start_date.slice(0,7))throw new Error('This month is before the loan start');if(next.emi_payments.some(p=>p.emi_id===id&&p.month===month&&p.status==='paid'))throw new Error('This EMI is already paid');const paymentId=`emi-${id}-${month}`;const date=format(new Date(),'yyyy-MM-dd');next.emi_payments=next.emi_payments.filter(p=>!(p.emi_id===id&&p.month===month));next.emi_payments.push({id:paymentId,emi_id:id,month,amount:loan.emi_amount,status:'paid',paid_date:date});if(!next.categories.some(c=>c.id==='emi'))next.categories.push({id:'emi',name:'EMI',color:'#8c7bdf',type:'fixed',icon:'Landmark'});next.expenses.push({id:paymentId,amount:loan.emi_amount,date:`${month}-${String(loan.due_day).padStart(2,'0')}`,note:loan.loan_name,category_id:'emi',payment_method:'Bank Transfer',is_recurring:false,tags:[],emi_id:id});loan.paid_months++;if(loan.paid_months>=loan.tenure_months)loan.status='closed';return next;}
export function months(end:string,count=6){return Array.from({length:count},(_,i)=>monthKey(addMonths(new Date(end+'-01T12:00:00'),i-count+1)));}
export function emptyState(name='Alex'):State{return {profile:{name,currency:'INR',salary_credit_day:1,salary_credit_rule:'fixed',monthly_salary:0,onboarded:false},incomes:[],expenses:[],categories:defaultCategories(),emis:[],emi_payments:[],budgets:[],goals:[],people:[],ledger_entries:[],repayments:[],attachments:[]};}
export function defaultCategories(){return ['Rent','Groceries','Food & Dining','Transport','Fuel','Utilities','Mobile & Internet','Shopping','Entertainment','Health','Education','Travel','Insurance','Subscriptions','Family','Investments','Miscellaneous','EMI'].map((name,i)=>({id:name==='EMI'?'emi':`cat-${i}`,name,icon:['Home','ShoppingBasket','Utensils','TrainFront','Fuel','Zap'][i%6],color:['#7666d5','#48b5a0','#f3ac65','#74a5e6','#e8869d','#a79bc8'][i%6],type:([0,5,6,12,13,17].includes(i)?'fixed':'variable') as 'fixed'|'variable'}));}
export function demoState(now=new Date()):State{const s=emptyState('Alex Morgan');s.profile.onboarded=true;s.profile.monthly_salary=85000;const current=monthKey(now);for(const [mi,m] of months(current).entries()){s.incomes.push({id:`salary-${m}`,amount:85000,source_type:'Salary',date:`${m}-01`,note:'Monthly salary · Acme Studio',is_recurring:mi===5,salary_schedule:mi===5,tags:[]});s.incomes.push({id:`freelance-${m}`,amount:mi===5?18000:12000+mi*1000,source_type:'Freelance',date:`${m}-08`,note:'Brand design project',is_recurring:false,tags:[]});const days=m===current?now.getDate():28;for(let i=0;i<22;i++){const cat=[0,1,2,3,4,5,6,7,8,9,13][i%11];const day=Math.min(days,1+Math.floor(i*1.25));s.expenses.push({id:`expense-${m}-${i}`,amount:cat===0?(i===0?18000:0):Math.round([950,1850,680,420,1800,1400,799,2200,549,850,499][i%11]*(1+(mi%3)*0.1)),category_id:`cat-${cat}`,date:`${m}-${String(day).padStart(2,'0')}`,note:['Apartment rent','Fresh groceries','Weekend dinner','Metro & commute','Petrol refill','Electricity bill','Mobile plan','A little something','Movie night','Pharmacy','Spotify Premium'][i%11],payment_method:(['Bank Transfer','UPI','Card','Cash'] as const)[i%4],is_recurring:false,tags:[]});}s.expenses=s.expenses.filter(e=>e.amount>0);}
 s.emis=[{id:'loan-car',loan_name:'Car loan',lender:'HDFC Bank',loan_type:'Car',principal:480000,interest_rate:8.5,emi_amount:9848,tenure_months:60,start_date:format(addMonths(startOfMonth(now),-17),'yyyy-MM-dd'),due_day:5,paid_months:18,status:'active'},{id:'loan-laptop',loan_name:'MacBook Pro',lender:'ICICI Bank',loan_type:'Personal',principal:120000,interest_rate:0,emi_amount:10000,tenure_months:12,start_date:format(addMonths(startOfMonth(now),-5),'yyyy-MM-dd'),due_day:28,paid_months:5,status:'active'}];
 for(const m of months(current)){for(const loan of s.emis){if(m===current&&now.getDate()<loan.due_day)continue;const id=`emi-${loan.id}-${m}`;s.emi_payments.push({id,emi_id:loan.id,month:m,amount:loan.emi_amount,status:'paid',paid_date:`${m}-${String(loan.due_day).padStart(2,'0')}`});s.expenses.push({id,amount:loan.emi_amount,date:`${m}-${String(loan.due_day).padStart(2,'0')}`,note:loan.loan_name,category_id:'emi',payment_method:'Bank Transfer',is_recurring:false,tags:[],emi_id:loan.id});}}
 for(const m of months(current,2))for(const [category_id,limit_amount] of [['cat-1',6500],['cat-2',4000],['cat-7',6000],['cat-8',2000]] as const)s.budgets.push({id:`budget-${m}-${category_id}`,month:m,category_id,limit_amount});
 s.goals=[{id:'goal-1',name:'Japan adventure',target_amount:200000,saved_amount:125000,deadline:format(addMonths(now,8),'yyyy-MM-dd'),icon:'Plane'},{id:'goal-2',name:'Emergency fund',target_amount:300000,saved_amount:186000,deadline:format(addMonths(now,12),'yyyy-MM-dd'),icon:'ShieldCheck'},{id:'goal-3',name:'A new workspace',target_amount:80000,saved_amount:24000,deadline:format(addMonths(now,6),'yyyy-MM-dd'),icon:'Laptop'}];
 const created=now.toISOString();s.people=[{id:'person-rahul',name:'Rahul Sharma',phone:'919876543210',relation:'Friend',notes:'College friend',created_at:created},{id:'person-priya',name:'Priya Mehta',phone:'919812345678',relation:'Family',notes:'',created_at:created},{id:'person-amit',name:'Amit Patel',relation:'Colleague',notes:'',created_at:created},{id:'person-neha',name:'Neha Kapoor',relation:'Neighbour',notes:'',created_at:created}];
 const ago=(n:number)=>format(addMonths(now,-n),'yyyy-MM-dd'),today=format(now,'yyyy-MM-dd');s.ledger_entries=[{id:'ledger-rahul-settled',person_id:'person-rahul',direction:'GAVE',amount:2000,date:ago(3),due_date:ago(1),purpose:'Concert tickets',payment_method:'UPI',interest_enabled:false,remind:true,status:'SETTLED',written_off_amount:0,created_at:created},{id:'ledger-rahul',person_id:'person-rahul',direction:'GAVE',amount:5000,date:ago(1),due_date:format(addMonths(now,1),'yyyy-MM-dd'),purpose:'Travel booking',payment_method:'UPI',interest_enabled:false,remind:true,status:'PARTIAL',written_off_amount:0,created_at:created},{id:'ledger-priya',person_id:'person-priya',direction:'TOOK',amount:3000,date:ago(2),due_date:format(addMonths(now,1),'yyyy-MM-dd'),purpose:'Shared family purchase',payment_method:'Bank Transfer',interest_enabled:false,remind:true,status:'PARTIAL',written_off_amount:0,created_at:created},{id:'ledger-amit',person_id:'person-amit',direction:'GAVE',amount:4500,date:ago(2),due_date:format(addMonths(now,-1),'yyyy-MM-dd'),purpose:'Emergency help',payment_method:'UPI',interest_enabled:false,remind:true,status:'OVERDUE',written_off_amount:0,created_at:created},{id:'ledger-neha',person_id:'person-neha',direction:'GAVE',amount:1800,date:today,purpose:'Utility payment',payment_method:'Cash',via_name:'Rohan',on_behalf_of:'Building committee',interest_enabled:false,remind:false,status:'PENDING',written_off_amount:0,created_at:created},{id:'ledger-priya-2',person_id:'person-priya',direction:'GAVE',amount:2500,date:ago(4),purpose:'Gift contribution',payment_method:'UPI',interest_enabled:false,remind:false,status:'SETTLED',written_off_amount:0,created_at:created}];
 s.repayments=[{id:'repay-r1',ledger_entry_id:'ledger-rahul-settled',amount:1000,date:ago(2),payment_method:'UPI',note:'First half',created_at:created},{id:'repay-r2',ledger_entry_id:'ledger-rahul-settled',amount:1000,date:ago(1),payment_method:'UPI',note:'Final half',created_at:created},{id:'repay-r3',ledger_entry_id:'ledger-rahul',amount:1500,date:today,payment_method:'UPI',note:'Partial return',created_at:created},{id:'repay-p1',ledger_entry_id:'ledger-priya',amount:1000,date:today,payment_method:'Bank Transfer',note:'First repayment',created_at:created},{id:'repay-p2',ledger_entry_id:'ledger-priya-2',amount:2500,date:ago(3),payment_method:'UPI',note:'Settled',created_at:created}];
 const proof=(label:string)=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400"><rect width="100%" height="100%" fill="#eee9f7"/><text x="50%" y="48%" text-anchor="middle" font-family="sans-serif" font-size="28" fill="#7564ad">MoneyMate proof</text><text x="50%" y="58%" text-anchor="middle" font-family="sans-serif" font-size="18" fill="#9284a8">${label}</text></svg>`)}`;s.attachments=[{id:'proof-entry',ledger_entry_id:'ledger-rahul-settled',file_url:proof('Original transfer'),file_name:'transfer-proof.svg',file_type:'image',uploaded_at:created},{id:'proof-repay',repayment_id:'repay-r1',file_url:proof('Repayment received'),file_name:'repayment-proof.svg',file_type:'image',uploaded_at:created}];return s;}


