import { z } from 'zod';
const id = z.string().min(1).max(100);
const amount = z.number().finite().min(0).max(1e12);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => !isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0,10) === v, 'Enter a valid date');
export const categorySchema = z.object({ id, name:z.string().trim().min(1).max(60), color:z.string().regex(/^#[0-9a-fA-F]{6}$/), icon:z.string().max(40), type:z.enum(['fixed','variable']) });
export const transactionSchema = z.object({ id, amount:amount.positive(), date, note:z.string().max(500), is_recurring:z.boolean(), source_type:z.enum(['Salary','Freelance','Business','Rental','Bonus','Interest','Gift','Other']).optional(), category_id:id.optional(), payment_method:z.enum(['Cash','UPI','Card','Bank Transfer']).optional(), tags:z.array(z.string().max(40)).max(20).default([]), recurrence_id:id.optional(), emi_id:id.optional(), salary_schedule:z.boolean().optional() });
export const loanSchema = z.object({ id, loan_name:z.string().min(1).max(100), lender:z.string().max(100), loan_type:z.enum(['Home','Car','Bike','Personal','Education','Credit Card','Other']), principal:amount.positive(), interest_rate:z.number().min(0).max(60), emi_amount:amount.positive(), tenure_months:z.number().int().min(1).max(600), start_date:date, due_day:z.number().int().min(1).max(28), paid_months:z.number().int().min(0).max(600), status:z.enum(['active','closed']) });
export const budgetSchema = z.object({id,category_id:id,month:z.string().regex(/^\d{4}-\d{2}$/),limit_amount:amount.positive()});
export const goalSchema = z.object({id,name:z.string().min(1).max(100),target_amount:amount.positive(),saved_amount:amount,deadline:date,icon:z.string().max(40)});
export const personSchema=z.object({id,name:z.string().trim().min(1).max(100),phone:z.string().trim().max(30).optional(),relation:z.enum(['Friend','Family','Colleague','Neighbour','Other']),photo_url:z.string().max(2_000_000).optional(),notes:z.string().max(1000),created_at:z.string().datetime()});
export const ledgerEntrySchema=z.object({id,person_id:id,direction:z.enum(['GAVE','TOOK']),amount:amount.positive(),date,due_date:date.optional(),purpose:z.string().trim().min(1).max(500),payment_method:z.enum(['Cash','UPI','Card','Bank Transfer']),via_person_id:id.optional(),via_name:z.string().trim().max(100).optional(),on_behalf_of:z.string().trim().max(100).optional(),interest_rate:z.number().min(0).max(100).optional(),interest_enabled:z.boolean().default(false),no_return_expected:z.boolean().optional(),remind:z.boolean().default(true),status:z.enum(['PENDING','PARTIAL','SETTLED','OVERDUE','WRITTEN_OFF']).default('PENDING'),written_off_amount:amount.default(0),created_at:z.string().datetime()});
export const repaymentSchema=z.object({id,ledger_entry_id:id,amount:amount.positive(),date,payment_method:z.enum(['Cash','UPI','Card','Bank Transfer']),note:z.string().max(500),created_at:z.string().datetime()});
export const attachmentSchema=z.object({id,ledger_entry_id:id.optional(),repayment_id:id.optional(),file_url:z.string().max(7_500_000),file_name:z.string().min(1).max(255),file_type:z.enum(['image','pdf']),uploaded_at:z.string().datetime()}).refine(a=>Boolean(a.ledger_entry_id)!==Boolean(a.repayment_id),'Proof must belong to one entry or repayment');
export const stateSchema = z.object({profile:z.object({name:z.string().trim().min(1).max(80),currency:z.literal('INR'),salary_credit_day:z.number().int().min(1).max(31).default(1),salary_credit_rule:z.enum(['fixed','last_working_day','before_last_working_day','manual']).default('fixed'),monthly_salary:amount.default(0),onboarded:z.boolean()}),incomes:z.array(transactionSchema).max(20000),expenses:z.array(transactionSchema).max(20000),categories:z.array(categorySchema).max(200),emis:z.array(loanSchema).max(100),emi_payments:z.array(z.object({id,emi_id:id,month:z.string().regex(/^\d{4}-\d{2}$/),amount:amount.positive(),status:z.enum(['paid','pending','overdue']),paid_date:date.optional()})).max(10000),budgets:z.array(budgetSchema).max(5000),goals:z.array(goalSchema).max(200),people:z.array(personSchema).max(1000).default([]),ledger_entries:z.array(ledgerEntrySchema).max(10000).default([]),repayments:z.array(repaymentSchema).max(50000).default([]),attachments:z.array(attachmentSchema).max(50000).default([])}).superRefine((s,ctx)=>{
  const fail=(message:string)=>ctx.addIssue({code:'custom',message});
  for(const list of [s.incomes,s.expenses,s.categories,s.emis,s.emi_payments,s.budgets,s.goals,s.people,s.ledger_entries,s.repayments,s.attachments]) if(new Set(list.map(x=>x.id)).size!==list.length) fail('Duplicate record IDs');
  const cats=new Set(s.categories.map(c=>c.id)); const loans=new Set(s.emis.map(e=>e.id));
  if(s.expenses.some(e=>!e.category_id || !cats.has(e.category_id))) fail('Unknown expense category');
  if(s.incomes.some(e=>!e.source_type)) fail('Income source is required');
  if(s.budgets.some(b=>!cats.has(b.category_id))) fail('Unknown budget category');
  if(new Set(s.budgets.map(b=>b.month+b.category_id)).size!==s.budgets.length) fail('Only one budget per category and month');
  if(s.emis.some(e=>e.paid_months>e.tenure_months)) fail('Paid months exceeds tenure');
  if(s.emi_payments.some(p=>!loans.has(p.emi_id))) fail('Unknown loan');
  if(new Set(s.emi_payments.map(p=>p.emi_id+p.month)).size!==s.emi_payments.length) fail('Duplicate EMI payment');
  const people=new Set(s.people.map(p=>p.id)), entries=new Set(s.ledger_entries.map(e=>e.id)), repayments=new Set(s.repayments.map(r=>r.id));
  if(s.ledger_entries.some(e=>!people.has(e.person_id))) fail('Unknown person in ledger');
  if(s.repayments.some(r=>!entries.has(r.ledger_entry_id))) fail('Unknown ledger entry in repayment');
  if(s.attachments.some(a=>(a.ledger_entry_id&&!entries.has(a.ledger_entry_id))||(a.repayment_id&&!repayments.has(a.repayment_id)))) fail('Unknown proof owner');
  for(const entry of s.ledger_entries){const repaid=s.repayments.filter(r=>r.ledger_entry_id===entry.id).reduce((n,r)=>n+r.amount,0);if(repaid+entry.written_off_amount>entry.amount+(entry.interest_enabled?entry.amount*(entry.interest_rate||0)*Math.max(0,(Date.now()-Date.parse(entry.date+'T12:00:00'))/86400000)/36500:0)+0.01)fail('Repayments cannot exceed the pending amount');}
});
export type State=z.infer<typeof stateSchema>;
export type Transaction=z.infer<typeof transactionSchema>;
export type Loan=z.infer<typeof loanSchema>;
export type Category=z.infer<typeof categorySchema>;
export type Goal=z.infer<typeof goalSchema>;
export type Person=z.infer<typeof personSchema>;
export type LedgerEntry=z.infer<typeof ledgerEntrySchema>;
export type Repayment=z.infer<typeof repaymentSchema>;
export type Attachment=z.infer<typeof attachmentSchema>;
